### ISSUE TITLE
I can't install version 0.044

### ISSUE THREAD

**Issue by JJ** [cpanxaoc/perl-Glib-Object-Introspection#1]
I finally found [this solution](https://github.com/leafo/gifine/issues/1) which implies installing something completely different, libgirepository. It still fails, though.

**Comment by cpanxaoc** [comment]
Hi, this is not an official support channel for G:O:I.  Please post your problem to the mailing list, along with any command output.  I'll be deleting this issue right after this comment gets sent out.
